ccflags-y += -Wno-error=strict-prototypes -Wno-error=implicit-function-declaration
obj-$(CONFIG_MTD_NAND_MESON6_AML) += meson6_aml_nand.o
meson6_aml_nand-y := aml_nand.o m3_nand.o
obj-$(CONFIG_MTD_NAND_MESON6_AML_NFTL) += aml_nftl/
